import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface CreateBookingRequest {
  holdId: string;
  vehicleId: string;
  locationId: string;
  startAt: string;
  endAt: string;
  dailyRate: number;
  totalDays: number;
  subtotal: number;
  taxAmount: number;
  depositAmount: number;
  totalAmount: number;
  addOns: Array<{
    addOnId: string;
    price: number;
    quantity: number;
  }>;
  notes?: string;
}

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    
    // Create admin client for transaction safety
    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

    // Get user from auth header
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "Missing authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Verify user token
    const supabaseClient = createClient(supabaseUrl, Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!, {
      global: { headers: { Authorization: authHeader } },
    });
    
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser();
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: "Invalid or expired session" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const body: CreateBookingRequest = await req.json();
    console.log("Creating booking for user:", user.id, "body:", body);

    const {
      holdId,
      vehicleId,
      locationId,
      startAt,
      endAt,
      dailyRate,
      totalDays,
      subtotal,
      taxAmount,
      depositAmount,
      totalAmount,
      addOns,
      notes,
    } = body;

    // Step 1: Verify hold is still active and belongs to user
    const { data: hold, error: holdError } = await supabaseAdmin
      .from("reservation_holds")
      .select("*")
      .eq("id", holdId)
      .eq("user_id", user.id)
      .eq("status", "active")
      .single();

    if (holdError || !hold) {
      console.log("Hold validation failed:", holdError);
      return new Response(
        JSON.stringify({ 
          error: "reservation_expired",
          message: "Your reservation has expired. Please start over." 
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if hold has expired
    if (new Date(hold.expires_at) < new Date()) {
      // Mark hold as expired
      await supabaseAdmin
        .from("reservation_holds")
        .update({ status: "expired" })
        .eq("id", holdId);

      return new Response(
        JSON.stringify({ 
          error: "reservation_expired",
          message: "Your reservation timer expired. Please start over." 
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Step 2: Double-check no conflicting bookings (race-safe)
    const { data: conflicts } = await supabaseAdmin
      .from("bookings")
      .select("id")
      .eq("vehicle_id", vehicleId)
      .in("status", ["pending", "confirmed", "active"])
      .or(
        `and(start_at.lte.${endAt},end_at.gte.${startAt})`
      )
      .limit(1);

    if (conflicts && conflicts.length > 0) {
      // Mark hold as expired since booking failed
      await supabaseAdmin
        .from("reservation_holds")
        .update({ status: "expired" })
        .eq("id", holdId);

      return new Response(
        JSON.stringify({ 
          error: "vehicle_unavailable",
          message: "This vehicle was just booked by another customer. Please choose a different vehicle." 
        }),
        { status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Step 3: Create the booking
    const { data: booking, error: bookingError } = await supabaseAdmin
      .from("bookings")
      .insert({
        user_id: user.id,
        vehicle_id: vehicleId,
        location_id: locationId,
        start_at: startAt,
        end_at: endAt,
        daily_rate: dailyRate,
        total_days: totalDays,
        subtotal: subtotal,
        tax_amount: taxAmount,
        deposit_amount: depositAmount,
        total_amount: totalAmount,
        booking_code: "", // Will be generated by trigger
        status: "confirmed",
        notes: notes || null,
      })
      .select()
      .single();

    if (bookingError) {
      console.error("Error creating booking:", bookingError);
      return new Response(
        JSON.stringify({ 
          error: "booking_failed",
          message: "Failed to create booking. Please try again." 
        }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log("Booking created:", booking.id);

    // Step 4: Create booking add-ons
    if (addOns && addOns.length > 0) {
      const addOnRecords = addOns.map((addon) => ({
        booking_id: booking.id,
        add_on_id: addon.addOnId,
        price: addon.price,
        quantity: addon.quantity,
      }));

      const { error: addOnsError } = await supabaseAdmin
        .from("booking_add_ons")
        .insert(addOnRecords);

      if (addOnsError) {
        console.error("Error creating add-ons:", addOnsError);
        // Don't fail the booking, but log the error
      }
    }

    // Step 5: Create payment record (mock - pending)
    const { error: paymentError } = await supabaseAdmin
      .from("payments")
      .insert({
        booking_id: booking.id,
        user_id: user.id,
        amount: totalAmount,
        payment_type: "rental",
        status: "completed",
        payment_method: "card",
        transaction_id: `mock_${Date.now()}`,
      });

    if (paymentError) {
      console.error("Error creating payment:", paymentError);
    }

    // Step 6: Mark hold as converted
    await supabaseAdmin
      .from("reservation_holds")
      .update({ status: "converted" })
      .eq("id", holdId);

    console.log("Booking complete:", booking.booking_code);

    return new Response(
      JSON.stringify({ 
        success: true,
        booking: {
          id: booking.id,
          bookingCode: booking.booking_code,
          status: booking.status,
        }
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Unexpected error:", error);
    return new Response(
      JSON.stringify({ 
        error: "server_error",
        message: "An unexpected error occurred. Please try again." 
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
