import { useState, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { FileText, CheckCircle, PenLine, Loader2, Download, FileDown } from "lucide-react";
import { useRentalAgreement, useSignAgreement } from "@/hooks/use-rental-agreement";
import { format } from "date-fns";
import { generateRentalAgreementPdf } from "@/lib/pdf/rental-agreement-pdf";
import { AgreementStructuredView } from "@/components/booking/AgreementStructuredView";
import { toast } from "sonner";

interface RentalAgreementSignProps {
  bookingId: string;
}

export function RentalAgreementSign({ bookingId }: RentalAgreementSignProps) {
  const { data: agreement, isLoading } = useRentalAgreement(bookingId);
  const signAgreement = useSignAgreement();
  
  const [signature, setSignature] = useState("");
  const [agreed, setAgreed] = useState(false);
  const contentRef = useRef<HTMLPreElement>(null);

  const handleSign = () => {
    if (!agreement || !signature.trim() || !agreed) return;
    signAgreement.mutate({
      agreementId: agreement.id,
      signature: signature.trim(),
      bookingId, // Pass bookingId for notification
    });
  };

  // Generate PDF from agreement content
  const handleDownloadPdf = async () => {
    if (!agreement) return;
    
    try {
      await generateRentalAgreementPdf(agreement, bookingId);
      toast.success("Agreement PDF downloaded");
    } catch (error) {
      console.error("PDF generation error:", error);
      toast.error("Failed to generate PDF");
    }
  };

  const handleDownloadTxt = () => {
    if (!agreement) return;
    const blob = new Blob([agreement.agreement_content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `rental-agreement-${bookingId.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <Card>
        <CardContent className="py-8 flex items-center justify-center">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  if (!agreement) {
    return (
      <Card className="border-dashed">
        <CardContent className="py-8 text-center text-muted-foreground">
          <FileText className="h-10 w-10 mx-auto mb-3 opacity-50" />
          <p>Rental agreement will be available once generated by staff.</p>
        </CardContent>
      </Card>
    );
  }

  const isSigned = agreement.status === "signed" || agreement.status === "confirmed";

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="h-5 w-5 text-primary" />
            <div>
              <CardTitle className="text-base">Rental Agreement</CardTitle>
              <CardDescription>
                {isSigned
                  ? `Signed on ${format(new Date(agreement.customer_signed_at!), "PPp")}`
                  : "Please review and sign before pickup"}
              </CardDescription>
            </div>
          </div>
          <Badge
            variant={
              agreement.status === "confirmed"
                ? "default"
                : agreement.status === "signed"
                ? "secondary"
                : "outline"
            }
          >
            {agreement.status === "confirmed"
              ? "Confirmed"
              : agreement.status === "signed"
              ? "Signed - Awaiting Confirmation"
              : "Pending Signature"}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Agreement Content */}
        <div className="border rounded-lg bg-muted/30">
          <ScrollArea className="h-64 p-4">
            <AgreementStructuredView agreement={agreement} bookingId={bookingId} />
          </ScrollArea>
        </div>

        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleDownloadPdf} className="gap-2">
            <FileDown className="h-4 w-4" />
            Download PDF
          </Button>
          <Button variant="ghost" size="sm" onClick={handleDownloadTxt} className="gap-2">
            <Download className="h-4 w-4" />
            TXT
          </Button>
        </div>

        {/* Signature Section */}
        {isSigned ? (
          <div className="bg-primary/5 border border-primary/20 rounded-lg p-4">
            <div className="flex items-center gap-3">
              <CheckCircle className="h-5 w-5 text-primary" />
              <div>
                <p className="font-medium">Signed by: {agreement.customer_signature}</p>
                <p className="text-sm text-muted-foreground">
                  {format(new Date(agreement.customer_signed_at!), "PPpp")}
                </p>
              </div>
            </div>
          </div>
        ) : (
          <>
            <Separator />

            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <Checkbox
                  id="agree"
                  checked={agreed}
                  onCheckedChange={(checked) => setAgreed(checked === true)}
                />
                <Label htmlFor="agree" className="text-sm leading-relaxed cursor-pointer">
                  I have read and agree to all terms and conditions outlined in this Rental
                  Agreement. I understand that my electronic signature has the same legal effect as
                  a handwritten signature.
                </Label>
              </div>

              <div className="space-y-2">
                <Label htmlFor="signature">Your Full Legal Name (as signature)</Label>
                <Input
                  id="signature"
                  placeholder="Type your full name to sign"
                  value={signature}
                  onChange={(e) => setSignature(e.target.value)}
                  disabled={signAgreement.isPending}
                />
              </div>

              <Button
                onClick={handleSign}
                disabled={!agreed || !signature.trim() || signAgreement.isPending}
                className="w-full gap-2"
              >
                {signAgreement.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Signing...
                  </>
                ) : (
                  <>
                    <PenLine className="h-4 w-4" />
                    Sign Agreement
                  </>
                )}
              </Button>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
